import type { HistoryData } from 'types';

export const historyData: HistoryData = [
  { id: '1', date: '10:46PM', title: 'Home', url: 'x.com' },
  { id: '2', date: '10:46PM', title: 'Trending Videos', url: 'youtube.com' },
  { id: '3', date: '10:47PM', title: 'How to Tie a Tie', url: 'google.com' },
  { id: '4', date: '10:48PM', title: 'Events Near Me', url: 'facebook.com' },
  { id: '5', date: '10:49PM', title: 'Latest News', url: 'twitter.com' },
  { id: '6', date: '10:50PM', title: 'Job Opportunities', url: 'linkedin.com' },
  { id: '7', date: '10:51PM', title: 'New Repo', url: 'github.com' },
  { id: '8', date: '10:52PM', title: 'JavaScript Question', url: 'stackoverflow.com' },
  { id: '9', date: '10:53PM', title: 'Tech Discussions', url: 'reddit.com' },
  { id: '10', date: '10:54PM', title: 'New Gadgets', url: 'amazon.com' },
  { id: '11', date: '10:55PM', title: 'Top Movies', url: 'netflix.com' },
  { id: '12', date: '10:56PM', title: 'Holiday Photos', url: 'instagram.com' },
  { id: '13', date: '10:57PM', title: 'DIY Crafts', url: 'pinterest.com' },
  { id: '14', date: '10:58PM', title: 'Healthy Recipes', url: 'allrecipes.com' },
  { id: '15', date: '10:59PM', title: 'Breaking News', url: 'bbc.com' },
  { id: '16', date: '11:00PM', title: 'Sports Highlights', url: 'espn.com' },
  { id: '17', date: '11:01PM', title: 'Weather Forecast', url: 'weather.com' },
  { id: '18', date: '11:02PM', title: 'Travel Destinations', url: 'lonelyplanet.com' },
  { id: '19', date: '11:03PM', title: 'Book Reviews', url: 'goodreads.com' },
  { id: '20', date: '11:04PM', title: 'Music Charts', url: 'billboard.com' },
  { id: '21', date: '11:05PM', title: 'Fashion Trends', url: 'vogue.com' },
  { id: '22', date: '11:06PM', title: 'Car Reviews', url: 'caranddriver.com' },
  { id: '23', date: '11:07PM', title: 'Stock Market News', url: 'bloomberg.com' },
  { id: '24', date: '11:08PM', title: 'Coding Tutorials', url: 'codecademy.com' },
  { id: '25', date: '11:09PM', title: 'Interior Design Tips', url: 'houzz.com' },
  { id: '26', date: '11:10PM', title: 'Workout Routines', url: 'bodybuilding.com' },
  { id: '27', date: '11:11PM', title: 'Pet Care', url: 'petmd.com' },
  { id: '28', date: '11:12PM', title: 'Mental Health Resources', url: 'psychologytoday.com' },
  { id: '29', date: '11:13PM', title: 'Online Courses', url: 'coursera.org' },
  { id: '30', date: '11:14PM', title: 'Game Reviews', url: 'ign.com' },
  { id: '31', date: '11:15PM', title: 'Local News', url: 'nytimes.com' },
  { id: '32', date: '11:16PM', title: 'Recipe Ideas', url: 'foodnetwork.com' },
];
